export const API_ERROR_CODES = {
  // 图像相关错误
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  IMAGE_FORMAT_INVALID: 'IMAGE_FORMAT_INVALID',
  IMAGE_RESOLUTION_TOO_LOW: 'IMAGE_RESOLUTION_TOO_LOW',
  IMAGE_CORRUPTED: 'IMAGE_CORRUPTED',
  IMAGE_EMPTY: 'IMAGE_EMPTY',
  
  // 分析相关错误
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  NO_SCALP_DETECTED: 'NO_SCALP_DETECTED',
  POOR_IMAGE_QUALITY: 'POOR_IMAGE_QUALITY',
  INSUFFICIENT_LIGHTING: 'INSUFFICIENT_LIGHTING',
  BLURRY_IMAGE: 'BLURRY_IMAGE',
  
  // 服务器错误
  SERVER_ERROR: 'SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  
  // 认证和授权错误
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  
  // 其他错误
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const;

export const ERROR_MESSAGES = {
  [API_ERROR_CODES.IMAGE_TOO_LARGE]: '图片大小超过限制，请上传小于 5MB 的图片',
  [API_ERROR_CODES.IMAGE_FORMAT_INVALID]: '不支持的图片格式，请上传 JPG 或 PNG 格式的图片',
  [API_ERROR_CODES.IMAGE_RESOLUTION_TOO_LOW]: '图片分辨率过低，请上传至少 1280x720 像素的图片',
  [API_ERROR_CODES.IMAGE_CORRUPTED]: '图片文件已损坏，请重新上传',
  [API_ERROR_CODES.IMAGE_EMPTY]: '请选择要上传的图片',
  
  [API_ERROR_CODES.ANALYSIS_FAILED]: '分析过程出现错误，请稍后重试',
  [API_ERROR_CODES.NO_SCALP_DETECTED]: '未能检测到头皮区域，请确保图片中包含清晰的头皮部分',
  [API_ERROR_CODES.POOR_IMAGE_QUALITY]: '图片质量不佳，请在光线充足的环境下重新拍摄',
  [API_ERROR_CODES.INSUFFICIENT_LIGHTING]: '图片光线不足，请在明亮环境下重新拍摄',
  [API_ERROR_CODES.BLURRY_IMAGE]: '图片模糊，请保持手机稳定并重新拍摄',
  
  [API_ERROR_CODES.SERVER_ERROR]: '服务器内部错误，请稍后重试',
  [API_ERROR_CODES.SERVICE_UNAVAILABLE]: '服务暂时不可用，请稍后重试',
  [API_ERROR_CODES.RATE_LIMIT_EXCEEDED]: '请求频率过高，请稍后再试',
  
  [API_ERROR_CODES.UNAUTHORIZED]: '请先登录后再进行操作',
  [API_ERROR_CODES.FORBIDDEN]: '您没有权限执行此操作',
  [API_ERROR_CODES.SUBSCRIPTION_EXPIRED]: '您的订阅已过期，请续费后继续使用',
  
  [API_ERROR_CODES.INVALID_REQUEST]: '无效的请求，请检查输入参数',
  [API_ERROR_CODES.VALIDATION_ERROR]: '输入验证失败，请检查输入内容',
  [API_ERROR_CODES.UNKNOWN_ERROR]: '发生未知错误，请稍后重试'
} as const;

export const ERROR_SUGGESTIONS = {
  [API_ERROR_CODES.IMAGE_TOO_LARGE]: '请尝试压缩图片后重新上传',
  [API_ERROR_CODES.IMAGE_FORMAT_INVALID]: '请将图片转换为支持的格式后重新上传',
  [API_ERROR_CODES.IMAGE_RESOLUTION_TOO_LOW]: '请使用更高分辨率的相机拍摄',
  [API_ERROR_CODES.IMAGE_CORRUPTED]: '请重新拍摄或选择其他图片',
  [API_ERROR_CODES.IMAGE_EMPTY]: '请选择一张有效的图片',
  
  [API_ERROR_CODES.ANALYSIS_FAILED]: '如果问题持续存在，请联系客服支持',
  [API_ERROR_CODES.NO_SCALP_DETECTED]: '请确保图片中包含完整的头皮区域，并且光线充足',
  [API_ERROR_CODES.POOR_IMAGE_QUALITY]: '请在光线充足的环境下，使用手机后置摄像头重新拍摄',
  [API_ERROR_CODES.INSUFFICIENT_LIGHTING]: '请在自然光或明亮的室内灯光下重新拍摄',
  [API_ERROR_CODES.BLURRY_IMAGE]: '请使用三脚架或保持手机稳定后重新拍摄',
  
  [API_ERROR_CODES.SERVER_ERROR]: '如果问题持续存在，请报告给技术支持团队',
  [API_ERROR_CODES.SERVICE_UNAVAILABLE]: '请等待几分钟后重试，或检查服务状态页面',
  [API_ERROR_CODES.RATE_LIMIT_EXCEEDED]: '请降低请求频率，每分钟最多发送 5 次请求',
  
  [API_ERROR_CODES.UNAUTHORIZED]: '请点击右上角的登录按钮进行账号登录',
  [API_ERROR_CODES.FORBIDDEN]: '如需更高权限，请升级您的账号等级',
  [API_ERROR_CODES.SUBSCRIPTION_EXPIRED]: '请访问账户页面进行续费操作',
  
  [API_ERROR_CODES.INVALID_REQUEST]: '请检查输入参数是否符合要求',
  [API_ERROR_CODES.VALIDATION_ERROR]: '请根据错误提示修正输入内容',
  [API_ERROR_CODES.UNKNOWN_ERROR]: '请刷新页面重试，如果问题持续存在请联系支持团队'
} as const; 